name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./Tools_Practice5.sln
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Tools_Practice5.sln
    - name: Publish
      run: dotnet publish ./Tools_Practice5.sln
    - uses: actions/upload-artifact@v2
      with:
        name: release.zip
        path: home/runner/work/Tools_Practice5/Tools_Practice5/Tools_Practice5/bin/Debug/net5.0/publish/
    

