name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./Tools_Practice5.sln
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Tools_Practice5.sln
    - name: Publish
      run: dotnet publish ./Tools_Practice5.sln
    - name: Easy Zip Files
      # You may pin to the exact commit or the version.
      # uses: vimtor/action-zip@5f1c4aa587ea41db1110df6a99981dbe19cee310
      uses: vimtor/action-zip@v1
      with:
        # Files or directories to zip
        files: ./Tools_Practice5.sln
        # Name of output zip file
        dest: release.zip
        # Whether to add subdirectories to simply zip all files to the root
        recursive: default
    

